### ISSUE TITLE
Not reading asdf ruby version when inside tmux

### ISSUE THREAD

**Issue by iamarmanjon** [thoughtbot/dotfiles#587] opened 2018-02-27 16:23 UTC
Hey guys, anyone experience this problem too? Basically, when I'm inside tmux, my ruby version is using the local one instead of from asdf. I even tried doing `asdf global ruby 2.5.0`,  but my ruby version is not changing. I also tried commenting out my whole `~/.tmux.conf` and `~/.tmux.conf.local`. I'm not sure what's causing the issue.

Here are some screenshots. First one is just zsh, and last is inside tmux.

![screen shot 2018-02-28 at 12 17 19 am](https://user-images.githubusercontent.com/7567758/36740303-fdea72f0-1c1c-11e8-941a-ebed3943fc8a.png)
![screen shot 2018-02-28 at 12 17 26 am](https://user-images.githubusercontent.com/7567758/36740304-fe261526-1c1c-11e8-8751-d77ccbadaa72.png)

**Comment by geoffharcourt** [comment] 2018-02-27 17:15
Could this be an issue of tmux not loading a login shell?

**Comment by gylaz** [comment] 2018-02-27 18:09
I ran into this recently as well. My best guess is it has something to do with the `path_helper` with tmux as I saw my path getting re-ordered on tmux start-up. I ended up doing [this suggestion](https://apple.stackexchange.com/a/248820).

**Comment by croaky** [comment] 2018-02-27 19:32
Maybe another approach:

```
# zshrc
PATH="$HOME/.asdf/bin:$PATH"
PATH="$HOME/.asdf/shims:$PATH"
```

Two differences than current thoughtbot/dotfiles:

* Inline the work done by `source`ing `$HOME/.asdf/asdf.sh`
* `PATH` alterations co-located in `zshrc` rather than `zsh/configs/post/path.zsh`, which is, in turn `source`ed by `zshrc`

Dunno if the subshell within subshell might be the cause but [this](https://github.com/statusok/statusok/blob/master/dotfiles/shell/zshrc#L133-L152) has resulted in the same `path` output for me outside and inside in `tmux`.

I personally find the manual `PATH` building a little easier to read and understand, too.

**Comment by jferris** [comment] 2018-02-27 20:00
Have you overridden the default shell or default command? By default, tmux starts your default shell as a login shell. If you haven't changed either of those, `$PATH` in `tmux` should be the same as `$PATH` in `$SHELL -l`.

You can also type `logout` from a shell to see if it's a login shell or not. (It will say "not login shell" if it's not.)

From `man tmux`:

             default-command shell-command
                     Set the command used for new windows (if not specified when the window
                     is created) to shell-command, which may be any sh(1) command.  The
                     default is an empty string, which instructs tmux to create a login
                     shell using the value of the default-shell option.

             default-shell path
                     Specify the default shell.  This is used as the login shell for new
                     windows when the default-command option is set to empty, and must be
                     the full path of the executable.  When started tmux tries to set a
                     default value from the first suitable of the SHELL environment vari‐
                     able, the shell returned by getpwuid(3), or /bin/sh.  This option
                     should be configured when tmux is used as a login shell.

**Comment by gylaz** [comment] 2018-02-28 05:32
When I start `tmux` and print `$PATH` as the first thing in `~/.zsh/configs/post/path.zsh`, it seems to preserve the full path from my existing/parent/iTerm shell. But starting a new iTerm tab, that same print results in just `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`. Maybe the fact that parent `$PATH` is preserved when `tmux` session is started, is causing `path_helper` to do something unexpected?

**Comment by gylaz** [comment] 2018-02-28 05:56
Interesting that `$SHELL -l` does produce the same `$PATH` as `tmux`.
However, iTerm/terminal.app (new window or tab) produce a different, "correct" `$PATH`.

**Comment by jferris** [comment] 2018-02-28 15:13
It looks like my OS (Arch Linux) is configured to rebuild `PATH` from scratch for each zsh login shell, which means starting a login shell within another shell will construct the same `PATH`. MacOS must do something different, so there are more possible `PATH` configurations depending on how a shell was started and what kind of shell it was started from.

If your OS is funny about login shells within shells, you can use this in `tmux.conf` to start an interactive shell instead of a login shell:

    set -g default-command "${SHELL}"

Because every OS seems to configure `PATH` and zsh differently, it's hard to have a setting in the dotfiles that works for everybody. What we're doing right now follows the recommendations for asdf (configure from `.zshrc`) and tmux (use a login shell).

That being said, I don't understand why @croaky's change fixes this. It seems like it should be a shorter way of doing the same thing, so there's still a piece of this puzzle that I'm missing.

**Comment by croaky** [comment] 2018-02-28 17:04
> What we're doing right now follows the recommendations for asdf (configure from `.zshrc`)

Possible variance from ASDF's recommendation:

* What does [this `if` statement](https://github.com/thoughtbot/dotfiles/blob/master/zshrc#L36) do? Could it be failing in some tmux scenarios? Could try moving the contents of `zsh/configs/post/path.zsh` into `zshrc` directly, seeing if there's a difference.
* Individuals' [`.zshrc.local`](https://github.com/thoughtbot/dotfiles/blob/master/zshrc#L45) overrides overriding the `PATH`.

**Comment by gylaz** [comment] 2018-02-28 17:07
@jferris The reason @croaky's method works (for me at least), is because `~/.asdf/asdf.sh` won't add to `$PATH` if its paths are already present (via `[[ ":$PATH:" != *":${ASDF_DIR}/bin:"* ]]` check).
@croaky is explicitly adding the needed paths in `. zshrc`.

When starting a tmux session, with:
```
# ~/.zshrc
echo $PATH
PATH="$HOME/.asdf/bin:$PATH"
PATH="$HOME/.asdf/shims:$PATH"
echo $PATH

...
```
the result is:
```
.git/safe/../../bin:/Users/greg/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/greg/Dev/bin:/Users/greg/.asdf/shims:/Users/greg/.asdf/bin:/Users/greg/.config/yarn/global/node_modules/.bin:/usr/local/opt/fzf/bin
/Users/greg/.asdf/shims:/Users/greg/.asdf/bin:.git/safe/../../bin:/Users/greg/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/greg/Dev/bin:/Users/greg/.config/yarn/global/node_modules/.bin:/usr/local/opt/fzf/bin
```
Oddly enough seems like `/Users/greg/.asdf/shims:/Users/greg/.asdf/bin` is being moved to the front rather then concated to the front (note the missing first occurence).

**Comment by jferris** [comment] 2018-02-28 18:27
@croaky - that `if` statement comes from #526, which fixed a bug with zcompiled configs (you don't source compiled config files directly, so it skips files ending in `.zwc`).

@gylaz - interesting - that `if` check isn't present in my `asdf.sh`. Looks like it was [added recently](https://github.com/asdf-vm/asdf/issues/261).

I think users in general will need to do one of:

1. Configure tmux not to use a login shell
2. Configure zsh to rebuild the `PATH` for each new login shell
3. Make your zsh configuration idempotent

I think the check in `asdf.sh` is intended to make things idempotent, but if I remember right, MacOS's `path_helper` will reorder entries that are already present, which means it will move its entries in front of asdf's. That basically means you need to do one of the first two things on MacOS, since `path_helper` is not idempotent.

**Comment by gohanlon** [comment] 2018-03-09 18:35
The asdf project has merged a [fix for this issue](asdf-vm/asdf#303).

While I think that fix does resolve this issue, I don't think that fix was quite right. I sketched out some [suggested code](https://github.com/asdf-vm/asdf/pull/303#issuecomment-371231967), and there's already [another PR](https://github.com/asdf-vm/asdf/pull/304) that incorporates part of what I recommended.

Please feel free to look over the above comment and PRs for correctness and make suggestions. Feedback from those with more shell scripting experience would be especially helpful.

**Comment by iamarmanjon** [comment] 2018-03-11 06:39
I use the current version of dotfiles on a fresh mac os, and I don't experienced anymore the problem I had. I guess the asdf issue is fixed now?

**Comment by jthegedus** [comment] 2018-03-12 01:25
@iamarmanjon A new version was published (after your post) to address these issues - https://github.com/asdf-vm/asdf/blob/master/CHANGELOG.md#043 . As stated by @gohanlon , there's still some edge cases that need to be addressed, but for the most part asdf now accounts for other tools rearranging the PATH segments.

**Comment by geoffharcourt** [comment] 2018-07-29 17:15
Since this appears to be caused by a now-fixed, asdf bug, I'm going to close this out.

**Closed by geoffharcourt** 2018-07-29 17:15 UTC

**Comment by n3rio** [comment] 2023-09-29 02:26
> Maybe another approach:
> 
> ```
> # zshrc
> PATH="$HOME/.asdf/bin:$PATH"
> PATH="$HOME/.asdf/shims:$PATH"
> ```
> 
> Two differences than current thoughtbot/dotfiles:
> 
>     * Inline the work done by `source`ing `$HOME/.asdf/asdf.sh`
> 
>     * `PATH` alterations co-located in `zshrc` rather than `zsh/configs/post/path.zsh`, which is, in turn `source`ed by `zshrc`
> 
> 
> Dunno if the subshell within subshell might be the cause but [this](https://github.com/statusok/statusok/blob/master/dotfiles/shell/zshrc#L133-L152) has resulted in the same `path` output for me outside and inside in `tmux`.
> 
> I personally find the manual `PATH` building a little easier to read and understand, too.

@croaky my env have been a total disaster sense i started to work on this rails, thank you!!!!!!!
