### ISSUE TITLE
I managed to get the `replace` function working on zsh

### ISSUE THREAD

**Issue by lucascaton** [thoughtbot/dotfiles#487] opened 2016-06-08 05:43 UTC
Hi there,

The [`replace function`](https://github.com/thoughtbot/dotfiles/blob/master/bin/replace) wasn't working to me, I'm using `zsh` but I'm not sure if this is related.
I was able to fix it by making [these changes](https://gist.github.com/lucascaton/ec3842384fc80e3e1ea7a3e35f811f72/revisions) and I can submit a PR if you're happy with this.

Cheers.

**Comment by blainesch** [comment] 2016-06-08 06:09
I'm using zsh and it's working for me. Also the line with `IFS=$'\n'` is important. See #479

**Comment by mrloop** [comment] 2016-06-09 09:27
`IFS=$'\n'` removing this line and the script works for me

**Comment by croaky** [comment] 2016-06-09 16:02
The replace function works for me as currently in this repo. I wonder if we can isolate why? I'm on zsh on OS X.

**Comment by mrloop** [comment] 2016-06-09 16:25
I'll have a dig later, any suggestions for debugging?

**Comment by mrloop** [comment] 2016-06-09 19:23
Installed from scratch in clean VM and working as expected in zsh on ubuntu 14.04. Must be some breaking config in current environment. Will update if I track it down.

**Comment by mike-burns** [comment] 2016-07-08 09:35
The `replace` command uses `/bin/sh`, not zsh. Can you confirm that `/bin/sh` is a POSIX shell? In the least, what is its file size? `\ls -l $(realpath /bin/sh) | awk '{print $5}'` will tell you. Is it a symlink? `readlink /bin/sh` will tell you.

OP's diff uses `"${(@f}....}"`, which is only available in zsh -- it splits `...` into an array on the newlines. POSIX sh (`/bin/sh`) does not have arrays.

**Comment by mrloop** [comment] 2016-07-08 09:52
@mike-burns not sure who you want a reply from
```
➜  ~ ls -l $(realpath /bin/sh) | awk '{print $5}'
154072
➜  ~ readlink /bin/sh
dash
```

**Comment by mike-burns** [comment] 2016-07-08 11:02
Thanks -- that approximately matches what I have on my system (Debian Jessie).

The best debugging trick is to add `set -x` after the `#!/bin/sh` in the `replace` script. Does that give any useful output?

**Comment by mrloop** [comment] 2016-07-08 12:51
I'm afraid I no longer have this issue, and the `replace` script now works as intended for me. I am unsure what change has resulted in it working and don't think I can do anymore useful debugging. If it happens again I'll update here. Since first posting here I've done a clean install of my OS and moved my /home partition onto a different file system.

**Comment by geoffharcourt** [comment] 2016-07-22 13:33
Closing this issue out unless we get a new report we can confirm. Thanks for letting us know, @mrloop.

**Closed by geoffharcourt** 2016-07-22 13:33 UTC
