### ISSUE TITLE
Unable to change windows - fresh install

### ISSUE THREAD

**Issue by noctrnal** [thoughtbot/dotfiles#460] opened 2015-12-09 15:44 UTC
Fresh install of thoughtbot/laptop and thoughtbot/dotfiles. When I have 2 vertical splits in vim, everything is superb. When I open a third, I cannot change windows to the new window. 

If remove `.vim/` and `.vimrc`, functionality is restored.

I have also tried multiple `rcup`s to see if that remedied the issue to no avail.

**Comment by noctrnal** [comment] 2015-12-09 15:51
Seems to work if I VS from the left-most window. Bugs otherwise.

**Comment by geoffharcourt** [comment] 2015-12-09 15:58
Hi @noctrnal, what version of Vim are you using? Are you using tmux? What OS?

**Comment by noctrnal** [comment] 2015-12-09 19:08
Using Vim version 7.4.944, not using tmux, and running El Capitan.

**Comment by geoffharcourt** [comment] 2015-12-09 19:52
@noctrnal does this happen with only thoughtbot/dotfiles in place with none of your own customizations? I took a peek at your dotfiles and it looks like you have some of your own Vim configuration that might be relevant.

**Comment by noctrnal** [comment] 2015-12-10 14:43
Happening with only thoughtbot/laptop and thoughtbot/dotfiles in place. The dotfiles on my github is not being used as the thoughtbot versions is about the best thing I've found. I've used these in previous dev environments without this problem. Possibly related to el capitan?

**Comment by geoffharcourt** [comment] 2015-12-10 14:45
@noctrnal sorry for all the questions, but this is an odd behavior from your editor. Which shortcut are you using to switch panes? Can you paste in the output from `:map` for that key-combination?

**Comment by noctrnal** [comment] 2015-12-10 18:59
No worries at all. I'm a big fan of the TB dotfiles, so glad to provide the additional information.

I'm using ```control + w``` + ```h|j|k|l``` to switch panes.

Wasn't sure how to get a ```:map``` for those specific commands so pasted whole output in ss's:

![screen shot 2015-12-10 at 12 58 38 pm](https://cloud.githubusercontent.com/assets/6752204/11725155/d0ca9b00-9f3d-11e5-9d6c-ffe001cdcb5d.png)
![screen shot 2015-12-10 at 12 56 43 pm](https://cloud.githubusercontent.com/assets/6752204/11725156/d0cac59e-9f3d-11e5-8f96-25274d6486f9.png)
![screen shot 2015-12-10 at 12 55 51 pm](https://cloud.githubusercontent.com/assets/6752204/11725157/d0cde15c-9f3d-11e5-9101-e1fa81491164.png)

**Comment by noctrnal** [comment] 2015-12-10 19:01
I've tried removing ```.vim``` and ```.vimrc```, verifying that the problem does not persist, reinstalling dotfiles, and confirming problem again crops up.

**Comment by geoffharcourt** [comment] 2015-12-10 19:13
I don't see anything there that looks suspicious, but can you paste the output of `:map <C-w>`? There's some results off the screen, and I just want to be sure we're not missing anything.

**Comment by geoffharcourt** [comment] 2015-12-10 19:13
Also, is this Terminal.app or iTerm 1/2?

**Comment by noctrnal** [comment] 2015-12-10 19:18
iTerm 2, build 2.1.4.

```:map <C-w>``` showing 'No mapping found'. Strange, can definitely ```control + w``` between panes.

**Comment by geoffharcourt** [comment] 2015-12-10 19:40
The `<C-w>` shortcuts you're using are built in to Vim, so they don't show up as mapped commands unless you've overridden them. I'll give this some more thought.

**Comment by geoffharcourt** [comment] 2015-12-18 22:32
@noctrnal I've been unable to recreate this in Vim 7.4.963 or Neovim. Could you update Vim to that patch and try once more?

**Comment by noctrnal** [comment] 2016-01-04 15:01
Upgraded Vim but went to 7.4.1016 in the upgrade. Same problem exists after reinstall. Should I try Vim 7.4.963?

**Comment by geoffharcourt** [comment] 2016-01-04 15:20
@noctrnal, no need to downgrade. At this point I'm not sure how to troubleshoot this beyond commenting out the entirety of `.vimrc` and then re-enabling it a line or chunk at a time until you identify the offending code. If you can figure out what setting breaks it on your machine we'll have a better place to start work on a fix.

**Comment by noctrnal** [comment] 2016-01-07 14:44
Have not had a chance to go through ```.vimrc``` to find which line(s) are griefing me, but I'm not seeing the same problem with Neovim.

**Comment by geoffharcourt** [comment] 2016-01-15 14:39
Hi @noctrnal, since we can't reproduce this on a bare Vim 7.4 or Neovim build, I suspect this is something going on with your personal configuration (maybe in your terminal?).

I'm going to close the issue, but if you isolate a particular line that's the cause, please reopen this issue and we can discuss.

**Closed by geoffharcourt** 2016-01-15 14:39 UTC
